### ISSUE TITLE
Text or code along side QR code

### ISSUE THREAD

**Issue by et-ent** [infocyph/OTP#23]
I am using this library for my  2FA.  I am wondering if there is a way to incorporate a string of common text or code that can be entered into the authentication app.  This would give an alternative to when cameras are acting up as well as provide a way to auto some testing we are doing.  I have seen this in other 2FA implementations and I am trying to be proactive with answers in the event that one of my managers asks me. Just curious.

**Comment by abmmhasan** [comment]
Thanks for reaching out. For which algorithm (TOTP/HOTP/OCRA) you expecting such feature?

**Comment by et-ent** [comment]
TOTP

**Comment by abmmhasan** [comment]
None of any existing client in curtrent market actually support this type of feature. We already have a parameter called $additionalParameters, which does accept such but, in that case you have to make your own App Clients.

Sorry for the late reply, here real life was bit busy!
